# Copyright (c) 2026 Salesforce, Inc.
# SPDX-License-Identifier: CC-BY-NC-4.0
#
# Licensed under the Creative Commons Attribution-NonCommercial 4.0
# International License. See LICENSE.txt in the repository root.

"""Public offline framework for prepared interview simulation."""

from .demo import deterministic_local_embedder, run_synthetic_demo
from .evaluation import (
    PERSONALITY_LEVEL_ORDINALS,
    BigFiveRating,
    BigFiveTrait,
    ContentSimilarityAggregate,
    ContentSimilarityJudgment,
    FactSummary,
    FactualConsistencyJudgment,
    FactualConsistencyLabel,
    PersonalityLevel,
    PersonalityTraitJudgment,
    PersonalityTraitVote,
    aggregate_content_similarity,
    big_five_alignment,
    build_content_similarity_prompt,
    build_fact_summary_prompt,
    build_factual_consistency_prompt,
    build_personality_similarity_prompt,
    contradiction_ratio,
    fact_summary_text,
    parse_content_similarity,
    parse_factual_consistency,
    parse_fact_summary,
    parse_personality_trait,
    vote_big_five,
    vote_personality_trait,
)
from .mcq import (
    AtomicItem,
    MCQAnswerScore,
    MCQItem,
    MCQOption,
    OptionKind,
    build_answer_prompt,
    build_atomic_item_prompt,
    build_distractor_prompt,
    build_mcq_answering_prompt,
    build_mcq_generation_prompt,
    exact_accuracy,
    mcq_reward,
    option_labels,
    parse_atomic_item,
    parse_distractors,
    parse_mcq_answer,
    parse_mcq_answers,
    parse_mcq_generation,
    score_mcq_answers,
    shuffle_mcq_item,
    shuffle_options,
)
from .prompts import (
    ChronologicalPromptBuilder,
    HybridPromptBuilder,
    LongProfilePromptBuilder,
    ProfilePromptBuilder,
    RandomPromptBuilder,
    ResponsePromptBuilder,
    ResponsePromptContext,
    RetrievalPromptBuilder,
    SimplePromptBuilder,
)
from .protocols import Embedder, Embedding, Model, call_embedder, call_model
from .retrieval import (
    RetrievalResult,
    cosine_similarity,
    rank_qa_pairs,
    retrieve_qa_pairs,
)
from .schema import (
    Interview,
    Personality,
    PreparedInterviewData,
    QAPair,
    SchemaValidationError,
    load_prepared_interviews,
    loads_prepared_interviews,
    parse_prepared_interviews,
)
from .split import (
    TEST_FRACTION,
    TemporalSplit,
    qa_pairs_from_interviews,
    sort_interviews,
    temporal_train_test_split,
)
from .statistics import Alternative, PermutationTestResult, paired_sign_flip_test


__all__ = [
    "Alternative",
    "AtomicItem",
    "BigFiveRating",
    "BigFiveTrait",
    "ChronologicalPromptBuilder",
    "ContentSimilarityAggregate",
    "ContentSimilarityJudgment",
    "Embedder",
    "Embedding",
    "FactualConsistencyJudgment",
    "FactualConsistencyLabel",
    "FactSummary",
    "HybridPromptBuilder",
    "Interview",
    "LongProfilePromptBuilder",
    "MCQItem",
    "MCQAnswerScore",
    "MCQOption",
    "Model",
    "OptionKind",
    "PERSONALITY_LEVEL_ORDINALS",
    "PermutationTestResult",
    "Personality",
    "PersonalityLevel",
    "PersonalityTraitJudgment",
    "PersonalityTraitVote",
    "PreparedInterviewData",
    "ProfilePromptBuilder",
    "QAPair",
    "RandomPromptBuilder",
    "ResponsePromptBuilder",
    "ResponsePromptContext",
    "RetrievalPromptBuilder",
    "RetrievalResult",
    "SchemaValidationError",
    "SimplePromptBuilder",
    "TEST_FRACTION",
    "TemporalSplit",
    "aggregate_content_similarity",
    "big_five_alignment",
    "build_answer_prompt",
    "build_atomic_item_prompt",
    "build_content_similarity_prompt",
    "build_distractor_prompt",
    "build_fact_summary_prompt",
    "build_factual_consistency_prompt",
    "build_mcq_answering_prompt",
    "build_mcq_generation_prompt",
    "build_personality_similarity_prompt",
    "call_embedder",
    "call_model",
    "contradiction_ratio",
    "cosine_similarity",
    "deterministic_local_embedder",
    "exact_accuracy",
    "fact_summary_text",
    "load_prepared_interviews",
    "loads_prepared_interviews",
    "mcq_reward",
    "option_labels",
    "paired_sign_flip_test",
    "parse_atomic_item",
    "parse_content_similarity",
    "parse_distractors",
    "parse_factual_consistency",
    "parse_fact_summary",
    "parse_mcq_answer",
    "parse_mcq_answers",
    "parse_mcq_generation",
    "parse_personality_trait",
    "parse_prepared_interviews",
    "qa_pairs_from_interviews",
    "rank_qa_pairs",
    "retrieve_qa_pairs",
    "run_synthetic_demo",
    "score_mcq_answers",
    "shuffle_mcq_item",
    "shuffle_options",
    "sort_interviews",
    "temporal_train_test_split",
    "vote_big_five",
    "vote_personality_trait",
]
